<a href="https://colab.research.google.com/github/kenneth-craig/academyPub/blob/main/ML-XGBoost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#upload sonar.csv file from local drive and import file
# load and summarize the sonar dataset
from google.colab import files
import pandas as pd
import numpy as np

diabities_data = files.upload()

Saving datasets-uci-breast-cancer.csv to datasets-uci-breast-cancer.csv


In [3]:
!pwd
!ls

/content
datasets-uci-breast-cancer.csv	sample_data


# Simple XGBoost Problem
**Using pima indians diabetes dataset**

In [ ]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

ds = np.loadtxt('/content/pima-indians-diabetes.data.csv', delimiter=',')

# Split into X & Y datset
# X is columns 0..7
# & is column 8 transposed
X = ds[:,0:8]
Y = ds[:,8]

# Split into TRAIN & TEST datasets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=7)

#fit model on training data
model = XGBClassifier()
model.fit(X_train, Y_train)

# make predictions for the test data
predictions = model.predict(X_test)

# evaluation predictions
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100))

Accuracy: 77.95%


# Using XGBoost to Predict Iris flower
**Label Encoding**

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

#load dataset
df = pd.read_csv('iris.csv', header=None)
ds = df.values

# Split the data into X and Y
X = ds[:,0:4]
Y = ds[:,4]

# Encode string class values as integers
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(Y)
le_y = label_encoder.transform(Y)

X_train, X_test, y_train, y_test = train_test_split(X, le_y, test_size=0.33, random_state=7)

# Fit model on training data
model = XGBClassifier()
model.fit(X_train, y_train)

#make predictions for test data
y_predictions = model.predict(X_test)

# Evaluate predictions
accuracy = accuracy_score(y_test, y_predictions)
print("Accuracy: %.2f%%" % (accuracy * 100))



Accuracy: 92.00%


# XGBoost with Categorical Data
**One Hot Encoding**

In [ ]:
import pandas as pd
from numpy import column_stack
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# Load data
df = pd.read_csv('/content/datasets-uci-breast-cancer.csv', header=None)

ds = df.values

# split into X & y
X = ds[:,0:9]
X = X.astype(str)
y = ds[:,9]

# Encode string input values as integers
columns = []
for i in range(0, X.shape[1]):
  label_encoder = LabelEncoder()
  feature = label_encoder.fit_transform(X[:,i])
  feature = feature.reshape(X.shape[0], 1)
  # print("feature_shape before onehot: ", feature.shape)
  onehot_encoder = OneHotEncoder(sparse=False, categories='auto')
  feature = onehot_encoder.fit_transform(feature)
  print("feature_shape after onehot: ", feature.shape)
  columns.append(feature)
  
# collapse columns into array
encoded_x = column_stack(columns)
print("encoded X shape: ", encoded_x.shape)

# encoding string class values as integers
label_encoder = LabelEncoder()
label_encoded_y = label_encoder.fit_transform(y)

# split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(encoded_x, label_encoded_y, test_size=0.33, random_state=7)

# fit model on training data
model = XGBClassifier()
model.fit(X_train, y_train)
print(model)

# make predictions for test data
y_predictions = model.predict(X_test)

# evaluate predictions
accuracy = accuracy_score(y_test, y_predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))


feature_shape after onehot:  (286, 6)
feature_shape after onehot:  (286, 3)
feature_shape after onehot:  (286, 11)
feature_shape after onehot:  (286, 7)
feature_shape after onehot:  (286, 3)
feature_shape after onehot:  (286, 3)
feature_shape after onehot:  (286, 2)
feature_shape after onehot:  (286, 6)
feature_shape after onehot:  (286, 2)
encoded X shape:  (286, 43)
XGBClassifier()
Accuracy: 71.58%


In [ ]:
print(type(encoded_x))
print(encoded_x)

<class 'numpy.ndarray'>
[[0. 0. 1. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 1. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [ ]:
df.head(3)

0          1        2  ...           7     8                       9
0  '40-49'  'premeno'  '15-19'  ...   'left_up'  'no'     'recurrence-events'
1  '50-59'     'ge40'  '15-19'  ...   'central'  'no'  'no-recurrence-events'
2  '50-59'     'ge40'  '35-39'  ...  'left_low'  'no'     'recurrence-events'

[3 rows x 10 columns]

In [ ]:
print(X)

[["'40-49'" "'premeno'" "'15-19'" ... "'3'" "'right'" "'left_up'"]
 ["'50-59'" "'ge40'" "'15-19'" ... "'1'" "'right'" "'central'"]
 ["'50-59'" "'ge40'" "'35-39'" ... "'2'" "'left'" "'left_low'"]
 ...
 ["'30-39'" "'premeno'" "'30-34'" ... "'2'" "'right'" "'right_up'"]
 ["'50-59'" "'premeno'" "'15-19'" ... "'2'" "'right'" "'left_low'"]
 ["'50-59'" "'ge40'" "'40-44'" ... "'3'" "'left'" "'right_up'"]]


In [ ]:
# Method for obtaining unique values for categories
list_col = df.columns.tolist()
for col in list_col:
   i = df.iloc[:,col].unique()
   print (col, ':- ', i)

0 :-  ["'40-49'" "'50-59'" "'60-69'" "'30-39'" "'70-79'" "'20-29'"]
1 :-  ["'premeno'" "'ge40'" "'lt40'"]
2 :-  ["'15-19'" "'35-39'" "'30-34'" "'25-29'" "'40-44'" "'10-14'" "'0-4'"
 "'20-24'" "'45-49'" "'50-54'" "'5-9'"]
3 :-  ["'0-2'" "'3-5'" "'15-17'" "'6-8'" "'9-11'" "'24-26'" "'12-14'"]
4 :-  ["'yes'" "'no'" nan]
5 :-  ["'3'" "'1'" "'2'"]
6 :-  ["'right'" "'left'"]
7 :-  ["'left_up'" "'central'" "'left_low'" "'right_up'" "'right_low'" nan]
8 :-  ["'no'" "'yes'"]
9 :-  ["'recurrence-events'" "'no-recurrence-events'"]


In [12]:
# Simplar code as above but used OrdinalLabeling for Age of person instead of OneHot and Accuracy results went down by 1%
import pandas as pd
from numpy import column_stack
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

# Load data
df = pd.read_csv('/content/datasets-uci-breast-cancer.csv', header=None)

ds = df.values

# split into X & y
X = ds[:,0:9]
X = X.astype(str)
y = ds[:,9]

# Encode string input values as integers
t = [('OrdAge', OrdinalEncoder(), [0]), ('hot', OneHotEncoder(), [1,2,3,4,5,6,7,8])]

transform = ColumnTransformer(transformers=t)

# transform the training data
encoded_x = transform.fit_transform(X)

# encode y output
label_encoder = LabelEncoder()
label_encoded_y = label_encoder.fit_transform(y)

# Create train/test dataset
X_train, X_test, y_train, y_test = train_test_split(encoded_x, label_encoded_y, test_size=0.33, random_state=7)

# Fit model on Training data
model = XGBClassifier();
model.fit(X_train, y_train)
print(model)

# Evaluate model
y_predictions = model.predict(X_test)

#evaluate predictions
accuracy = accuracy_score(y_test, y_predictions)
print("Accuracy %.2f%%" % (accuracy * 100))

XGBClassifier()
Accuracy 70.53%


In [4]:
# UNFINISHED CODE - Same code as above but trying to get it working using Pythonic with a For Next loop but didn't get it finished
import pandas as pd
from numpy import column_stack
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

# Load data
df = pd.read_csv('/content/datasets-uci-breast-cancer.csv', header=None)

ds = df.values

# split into X & y
X = ds[:,0:9]
X = X.astype(str)
Y = ds[:,9]

# Encode string input values as integers
t[0] = 'OrdAge', OrdinalEncoder(), [0]

t[1] "'hot', OneHotEncoder(), [1,2,3,4,5,6,7,8]"
t[1] = t1
t1 = "'hot', OneHotEncoder(), ["

for i in range (1, X.shape[1]):
  t1 = t1 + str(i)
  print(t1)

t1 = t1 + X.shape[1] + ']'
print(t1)

transform = ColumnTransformer(transformers=t)

# transform the training data
X_encoded = transformer.fit_transform(X)

# encode y output
label_encoder = LabelEncoder()
label_encoded_y = label_encoder.fit_transform(y)

# Create train/test dataset
X_train, X_test, y_train, y_test = train_test_split(X_encoded, label_encoded_y, test_size=0.33, random_state=7)

# Fit model on Training data
model = XGBClassifier();
model.fit(X_train, y_train)
print(model)

# Evaluate model
y_predictions = model.predict(X_test)

#evaluate predictions
accuracy = accuracy_score(y_test, y_predictions)
print("%.2f%%" % (accuracy * 100))

SyntaxError: ignored

In [ ]:
# UNFINISHED CODE: For Next loop to build command for COLUMN_TRANSFORMATION for OneHot Encoding all columns

from numpy import array

# Encode string input values as integers

t = []
#t[0] = 'OrdAge', OrdinalEncoder(), [0]

# format of t[1] = 'hot', OneHotEncoder(), [1,2,3,4,5,6,7,8]

t1 = "('hot', OneHotEncoder(), ["

for i in range (1, X.shape[1]):
  t1 = t1 + str(i)
  if i != X.shape[1]-1:
    t1 = t1 + ', '
  print(t1)

t1 = t1 + ']'
print(t1)

t[0] = ('OrdAge', OrdinalEncoder(), [0])
print('value of t0: ', t[0])
#print(type of )
print('value of t1: ', t[1])

print('value of t', t)

('hot', OneHotEncoder(), [1, 
('hot', OneHotEncoder(), [1, 2, 
('hot', OneHotEncoder(), [1, 2, 3, 
('hot', OneHotEncoder(), [1, 2, 3, 4, 
('hot', OneHotEncoder(), [1, 2, 3, 4, 5, 
('hot', OneHotEncoder(), [1, 2, 3, 4, 5, 6, 
('hot', OneHotEncoder(), [1, 2, 3, 4, 5, 6, 7, 
('hot', OneHotEncoder(), [1, 2, 3, 4, 5, 6, 7, 8
('hot', OneHotEncoder(), [1, 2, 3, 4, 5, 6, 7, 8]


IndexError: ignored

In [ ]:
X.shape

(286, 9)